#!/bin/bash

param=$1

if [ "$param" = "run" ]
	then
		# forward localhost
		ssh -R 80:127.0.0.1:5000 ssh.localhost.run &

		# start the python backend
		python ~/NestWatchServer/PythonBackend/TwilioBackend/NestWatch.py
elif [ "$param" = "update" ]
	then
		# run the updater
		sh ~/NestWatchServer/PythonBackend/TwilioBackend/update.sh
else
	echo "Invalid argument."
fi
